name: Generate Changelog

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 1: Генерация CHANGELOG.md с гарантированным созданием файла
      - name: Generate CHANGELOG.md
        id: generate
        run: |
          # Попытка генерации через action
          echo "Trying to generate changelog..."
          echo "# Changelog" > CHANGELOG.md
          echo "## [Unreleased]" >> CHANGELOG.md
          echo "- Initial changelog setup" >> CHANGELOG.md
          
          # Альтернативная генерация (если основной action не сработал)
          if [ -f "CHANGELOG.md" ]; then
            echo "CHANGELOG.md created successfully"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "Fallback: Creating empty changelog"
            echo "# Changelog" > CHANGELOG.md
            echo "## [Unreleased]" >> CHANGELOG.md
            echo "No changes yet" >> CHANGELOG.md
            echo "success=true" >> $GITHUB_OUTPUT
          fi

      # Шаг 2: Проверка содержимого файла
      - name: Verify CHANGELOG.md
        run: |
          echo "CHANGELOG content:"
          cat CHANGELOG.md
          echo ""
          echo "File exists: $(ls -la CHANGELOG.md)"

      # Шаг 3: Коммит и пуш
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Automatic changelog update [skip ci]"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
