name: Generate Changelog

on:
  workflow_dispatch:  # Только ручной запуск для тестов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate CHANGELOG.md
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: |
            categories:
              - title: "All Changes"
                labels: ["*"]  # Все PR, даже без меток

      - name: Debug files
        run: |
          ls -la
          if [ -f "CHANGELOG.md" ]; then
            echo "=== FILE CONTENT ==="
            cat CHANGELOG.md
          fi

      - name: Commit to main
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Add CHANGELOG.md"
          git push origin main
