name: Changelog Generator

on:
  push:
    tags:
      - 'v.1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: |
            categories:
              - title: "New Features"
                labels: ["feature"]
              - title: "Bug Fixes"
                labels: ["bug"]

