name: Generate Changelog

on:
  push:
    tags:
      - 'v*'  # Триггер на любые теги, начинающиеся с 'v'
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов для анализа изменений

      - name: Generate CHANGELOG.md
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toTag: v1.0.0    # Ваш текущий тег
          configuration: |
            categories:
              - title: "🚀 New Features"
                labels: ["feature", "enhancement"]
              - title: "🐛 Bug Fixes"
                labels: ["bug", "fix"]
              - title: "📚 Other Changes"
                labels: ["*"]  # Все остальные изменения

      - name: Verify and Commit
        run: |
          if [ -f "CHANGELOG.md" ]; then
            echo "Changelog content:"
            head -n 20 CHANGELOG.md  # Покажем начало файла для проверки
            
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add CHANGELOG.md
            git commit -m "Automatic changelog update for v1.0.0"
            git push
          else
            echo "Error: CHANGELOG.md not generated!"
            echo "Possible reasons:"
            echo "1. No closed PRs/issues found"
            echo "2. Configuration error"
            exit 1
          fi
