name: Generate Changelog

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Шаг 1: Генерация CHANGELOG.md (упрощённая конфигурация)
      - name: Generate CHANGELOG.md
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: |
            categories:
              - title: "All Changes"
                labels: ["*"]  # Включает ВСЕ закрытые PR
            issuesWoLabels: true  # Даже PR без меток

      # Шаг 2: Принудительное создание файла, если генератор не сработал
      - name: Create fallback CHANGELOG
        if: !steps.changelog.outputs.success
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "## [v1.0.0]" >> CHANGELOG.md
          echo "- Initial release" >> CHANGELOG.md

      # Шаг 3: Коммит и пуш
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Auto-generated changelog"
          git push
