name: Generate and Commit Changelog

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate CHANGELOG.md
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: |
            categories:
              - title: "🚀 Features"
                labels: ["feature"]

      - name: Commit and Push
        run: |
          if [ -f "CHANGELOG.md" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add CHANGELOG.md
            git commit -m "Update CHANGELOG.md"
            git push
          else
            echo "CHANGELOG.md not found!"
            exit 1
          fi
