name: Generate and Commit Changelog

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов

      - name: Generate CHANGELOG.md
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: |
            categories:
              - title: "Changes"
                labels: ["*"]  # Все типы PR

      - name: Check for CHANGELOG.md
        id: changelog
        run: |
          if [ -f "CHANGELOG.md" ]; then
            echo "CHANGELOG_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ CHANGELOG.md not generated! Check tags/PRs."
            exit 0  # Не останавливать workflow
          fi

      - name: Commit and Push
        if: steps.changelog.outputs.CHANGELOG_EXISTS == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Auto-update CHANGELOG.md"
          git push
