name: Generate and Commit Changelog

on:
  workflow_dispatch:  # Ручной запуск для тестов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate CHANGELOG.md
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: |
            categories:
              - title: "All Changes"
                labels: ["*"]
            issuesWoLabels: true  # Включает PR без меток

      - name: Check if file exists
        id: check_file
        run: |
          if [ -f "CHANGELOG.md" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "❌ Файл не создан! Проверьте теги/PR."
            exit 1
          fi

      - name: Commit and Push
        if: steps.check_file.outputs.exists == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push
