name: Generate Changelog

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions: 
  contents: write 

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create CHANGELOG.md
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "## [2025-04-28]" >> CHANGELOG.md
          echo "- Первая версия приложения, добавлены функции удаления и изменения еды, программы." >> CHANGELOG.md

      - name: Commit and Push
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              execSync('git config --global user.name "GitHub Actions"');
              execSync('git config --global user.email "actions@github.com"');
              execSync('git add CHANGELOG.md');
              execSync('git commit -m "Add CHANGELOG.md"');
              execSync(`git push https://${process.env.GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${process.env.GITHUB_REPOSITORY}.git HEAD:main`);
              console.log('CHANGELOG.md successfully pushed');
            } catch (error) {
              console.error('Error:', error.message);
              core.setFailed('Failed to push changes');
            }
